### ISSUE TITLE
[Closed] Whole series sub downloading not working properly 

### ISSUE THREAD

**Issue by i3p9** [Xonshiz/Hulu-Subs-Downloader#1]
So the cmd window closes after showing **Writing Links to the File...** for a split of second. 

Tried both the script and the binary for windows. 

Can you please help?

Also a suggestion: Can you add like SxxExx when writing the .srt files? Thanks!

**Comment by Xonshiz** [comment]
Could you please run the script in CMD rather than executing the script directly? Please post all the text that shows in the command windows here so I can see. And also post the URL you're trying to download from.

And for the naming, I'll look into it. I can't promise anything currently though.
