### ISSUE TITLE
text.encode("utf-8") Instead of str()

### ISSUE THREAD

**Issue by JadeErin** [Xonshiz/Hulu-Subs-Downloader#11]
I don't really know python. But I found that some episodes errored out because of character encoding problems. I was able to get them to work by changing str() to text.encode("utf-8") on line 52`data_json = json.loads((page_source.find_all('script', {'type': 'application/ld+json'})[0].text).encode('utf-8'))`

and line 72: `sub_file.write(smi_source.encode('utf-8'))`

**Comment by Xonshiz** [comment]
Thanks. Will check. Could you please also share a link to any such show/movie etc.?

**Comment by JadeErin** [comment]
https://www.hulu.com/watch/85098

**Comment by cangyuyao** [comment]
Thanks for this issue. Finally get it worked...

**Comment by Xonshiz** [comment]
I've pushed a new version for the tool and I've verified that this URL is working now.
P.S: Note that the URL you've posted here is old and HULU Doesn't use these IDs now. So, when you visit this link, Hulu will give you a new url. Use that URL.
Be sure to remove `?content_id=85098` from URL and it'll work.
