### ISSUE TITLE
SRT is causing too many new lines

### ISSUE THREAD

**Issue by JadeErin** [Xonshiz/Hulu-Subs-Downloader#12]
When converting to SRT format there are a lot of incorrect newlines being generated.

**Comment by Xonshiz** [comment]
could you share the srt and the vtt of that show?

**Comment by JadeErin** [comment]
https://www.hulu.com/watch/85090

You'll notice that the subtitle# and time codes are OK. But there seems the be an extra blank line preceding each subtitle line.

Also notice that in the VTT where a period ends a line it is often changed to a comma in the SRT version.

**Comment by Xonshiz** [comment]
I've pushed a new version for the tool and I've verified that this URL is working now.
P.S: Note that the URL you've posted here is old and HULU Doesn't use these IDs now. So, when you visit this link, Hulu will give you a new url. Use that URL.
Be sure to remove `?content_id=85090` from URL and it'll work.
