### ISSUE TITLE
attribute error/failure to execute?

### ISSUE THREAD

**Issue by seasalts** [Xonshiz/Hulu-Subs-Downloader#13]
![](https://i.gyazo.com/29bf2ee979ad69974886e19be76c88aa.png)

is there something i'm doing wrong?

edit: i've realized that the title of the show has a special character, FullMetal Alchemist: Brotherhood, I'm able to rip subs from other shows fine!

**Comment by Xonshiz** [comment]
I'll look into this.

**Comment by Xonshiz** [comment]
Similar to #18 .
