### ISSUE TITLE
Cannot Download Subtitles For Sonic X Japan Subbed Episode 71

### ISSUE THREAD

**Issue by ghost** [Xonshiz/Hulu-Subs-Downloader#14]
So I was downloading all of the English Subtitles for the Japan Dub of Sonic X, when I ran into this error: [https://cdn.discordapp.com/attachments/310416600635408384/434064460462686212/Error.PNG](url)

The Episode can be found here: https://www.hulu.com/watch/251398#i1,p68,d0

Is there any way to fix this?

**Comment by Xonshiz** [comment]
I've pushed a new version for the tool and I've verified that this URL is working now.
P.S: Note that the URL you've posted here is old and HULU Doesn't use these IDs now. So, when you visit this link, Hulu will give you a new url. Use that URL.
Be sure to remove `?content_id=251398` from URL and it'll work.
