### ISSUE TITLE
Some noob problems

### ISSUE THREAD

**Issue by clikkiepedia** [Xonshiz/Hulu-Subs-Downloader#15]
![firmx10vpxo](https://user-images.githubusercontent.com/40534660/41816616-3a2e5754-77a3-11e8-85ad-bab4ff49a9a8.jpg)
![m8ztksnxrjy](https://user-images.githubusercontent.com/40534660/41816617-3a6b6022-77a3-11e8-9e5f-413ce09d5d8f.jpg)
Hi! Idk why but the app just won't work it gives the error and shuts down immediately
Help please(

**Comment by Xonshiz** [comment]
Please follow #18 . More or less related.
