### ISSUE TITLE
Hulu Changed the System and software not working!

### ISSUE THREAD

**Issue by arbarbosa1979** [Xonshiz/Hulu-Subs-Downloader#18]
About seven months ago, it still works, but just few days ago, I logged on Hulu again and found that things kinda changed on Hulu and the software don't work anymore, can't download the subs anymore: 

```C:\MeusScripts\HuluDownloader>python HuluSubsDownloader.py
Enter a URL for hulu.com : http://www.hulu.com/oh-my-ghostess
Which format do you want? (SRT or VTT) : SRT

Please Check The URL again!

C:\MeusScripts\HuluDownloader>python HuluSubsDownloader.py
Enter a URL for hulu.com : https://www.hulu.com/series/oh-my-ghostess-422af229-57ad-4426-b821-9c3f568bbbe9
Which format do you want? (SRT or VTT) : srt

Please Check The URL again!

C:\MeusScripts\HuluDownloader>

**Comment by Xonshiz** [comment]
Yes, it's a known issue. I do have a way of getting the subs, but I don't really have a time to update this script. Maybe I'll take a look at it later on. I tried putting the working into this script, it didn't work.

**Comment by adrianlm1** [comment]
Any help on fixing this would be very much appreciated! (Y)

**Comment by Xonshiz** [comment]
Yeah, I found a way of getting that working. But, there was some issue with the cookies. I mean, there was some issue with the library that was handling the cookies and session. Will be able to take a look at it again later on. Not now.

**Comment by 323Wicked** [comment]
@Xonshiz Any chance of adding a way to also download video in the future?

**Comment by madnesofjuice** [comment]
Will you make this working again @Xonshiz ?

**Comment by DubbyParrot** [comment]
Any updates on this? Would be greatly appreciated. @Xonshiz

**Comment by FluffyDev2019** [comment]
Any updates on this issue and maby a new working windows exe to dl? 😀

**Comment by Xonshiz** [comment]
CI build seems to be failing. I'll take a look over the weekend and then around Sunday, I'll try to drop a working exe.

**Comment by theepicj19** [comment]
Hi there Xonshiz. After I enter the URL and it asks for SRT or VTT, no matter what I put in the whole thing will crash right after. Do you know about this bug? It says:

Enter a URL for hulu.com : https://www.hulu.com/watch/07fdd238-6c96-49e5-820a-1f7496005291
Which format do you want? (SRT or VTT) : SRT

Traceback (most recent call last):
  File "HuluSubsDownloader.py", line 127, in <module>
  File "HuluSubsDownloader.py", line 21, in __init__
  File "HuluSubsDownloader.py", line 52, in single_episode
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 90: ordinal not in range(128)
[19536] Failed to execute script HuluSubsDownloader

**Comment by clayton-grey** [comment]
It took me an embarrassingly long time to debug this, but the current version of BeautifulSoup doesn't accept javascript strings as "text", so:

` data_json = json.loads(str(page_source.find_all('script', {'type': 'application/json'})[0].text))`

needs to be

` data_json = json.loads(str(page_source.find_all('script', {'type': 'application/json'})[0].string))`

if you are getting an error on that line, as it's attempting to convert an empty string.

**Comment by bond485** [comment]
hi clayton-grey. i tried it,but still error
File HuluSubsDownloader.py", line 149, in <module>
    SubDownloader = HuluSubs(url=main_url, subtitle_type=sub_type)
  File HuluSubsDownloader.py", line 22, in __init__
    self.single_episode(self.url)
  File HuluSubsDownloader.py", line 63, in single_episode
    collection = [t for t in components if t["type"] == "collection_tabs"][0]["tabs"]
IndexError: list index out of range

**Comment by Xonshiz** [comment]
I'm not sure what's happening. I would need a Hulu login to see how things are working out. I'm trying for a free account, but, since Hulu isn't in my country and I don't really want to link my card with it, let's see how it goes.

**Comment by bond485** [comment]
> I'm not sure what's happening. I would need a Hulu login to see how things are working out. I'm trying for a free account, but, since Hulu isn't in my country and I don't really want to link my card with it, let's see how it goes.

i can give you a hulu account for test,if you have time. can you receive email on xonshiz@gmail.com? i can send account to you

**Comment by Xonshiz** [comment]
Yep, that would be great. You can send the credentials on that one. Thanks a lot @bond485 ! :)

**Comment by bond485** [comment]
> Yep, that would be great. You can send the credentials on that one. Thanks a lot @bond485 ! :)

i have send it to you, thanks a lot

**Comment by clayton-grey** [comment]
> hi clayton-grey. i tried it,but still error

I cannot debug for you, but that looks like the error I was getting. It has been a while, so I do not remember it perfectly, but the issue is that the data cannot be fetched because BeautifulSoup is attempting to scrape the javascript code which contains the correct URL codes's for fetching the subtitle data for the given show URL - the whole reason this script is needed is because Hulu made it obtuse to find where the actual subtitle data lives. The originally posted code used the .text, which BeautifulSoup used to recognized with Javascript. The current version does not seem to; .string should return the correct block of javascript text for parsing. (You can debug this and see for yourself by finding "collection_tabs" bit in the Hulu source data, which helped me figure out which part of the source BeautifulSoup was trying to scrape in the early part of the script. You can do the whole process yourself by hand, of course, but it would be quite slow!)

**Comment by Xonshiz** [comment]
I've finally pushed an update to this tool. Do go through the new updated documentation because a lot of things have been changed and new features (proxy support, cli arguments etc.) have been added.

If anyone finds or gets a new bug, please feel free to open a new Issue.
