### ISSUE TITLE
No subtitles are downloaded in TTML format

### ISSUE THREAD

**Issue by ghost** [Xonshiz/Hulu-Subs-Downloader#28]
When I try to download the subtitles of the TV show "Castle Rock" or "Bob's Burgers" in "ttml" format the script downloads only the first episode, but when I go to the folder of the downloaded subtitles no subtitles are actually downloaded and the folder is empty, my operating system is Windows 10, and I'm using a Windows EXE Binary.

https://www.hulu.com/series/castle-rock-b11816c9-9e35-44f3-bf04-220b1d12f770

https://www.hulu.com/series/bobs-burgers-fdeb1018-4472-442f-ba94-fb087cdea069

![15](https://user-images.githubusercontent.com/84876906/120540043-85d3a080-c3e8-11eb-90cb-23b14820d0a7.png)

Hulusubs_dl_Error_Log for "Castle Rock"

[Hulusubs_dl_Error_Log.zip](https://github.com/Xonshiz/Hulusubs_dl/files/6587130/Hulusubs_dl_Error_Log.zip)

**Comment by ghost** [comment]
@Xonshiz When I replaced in `hulu.py`

`if extension == 'srt':`

with

`if not extension == 'srt':`

and in `subtitle_processing.py` I replaced 

    replacement = re.sub(r'(\d\d:\d\d:\d\d).(\d\d\d) --> (\d\d:\d\d:\d\d).(\d\d\d)(?:[ \-\w]+:[\w\%\d:]+)*\n',
                         r'\1,\2 --> \3,\4\n', file_contents)
    replacement = re.sub(r'(\d\d:\d\d).(\d\d\d) --> (\d\d:\d\d).(\d\d\d)(?:[ \-\w]+:[\w\%\d:]+)*\n',
                         r'\1,\2 --> \3,\4\n', replacement)
    replacement = re.sub(r'(\d\d).(\d\d\d) --> (\d\d).(\d\d\d)(?:[ \-\w]+:[\w\%\d:]+)*\n', r'\1,\2 --> \3,\4\n',
                         replacement)
    replacement = re.sub(r'WEBVTT\n', '', replacement)
    replacement = re.sub(r'Kind:[ \-\w]+\n', '', replacement)
    replacement = re.sub(r'Language:[ \-\w]+\n', '', replacement)
    replacement = re.sub(r'<c[.\w\d]*>', '', replacement)
    replacement = re.sub(r'</c>', '', replacement)
    replacement = re.sub(r'<\d\d:\d\d:\d\d.\d\d\d>', '', replacement)
    replacement = re.sub(r'::[\-\w]+\([\-.\w\d]+\)[ ]*{[.,:;\(\) \-\w\d]+\n }\n', '', replacement)
    replacement = re.sub(r'Style:\n##\n', '', replacement)

with

    replacement = re.sub(r'(\d\d:\d\d:\d\d).(\d\d\d) --> (\d\d:\d\d:\d\d).(\d\d\d)(?:[ \-\w]+:[\w\%\d:]+)*\n',
                         r'\1.\2 --> \3.\4\n', file_contents)
    #replacement = re.sub(r'(\d\d:\d\d).(\d\d\d) --> (\d\d:\d\d).(\d\d\d)(?:[ \-\w]+:[\w\%\d:]+)*\n',
    #                     r'\1,\2 --> \3,\4\n', replacement)
    #replacement = re.sub(r'(\d\d).(\d\d\d) --> (\d\d).(\d\d\d)(?:[ \-\w]+:[\w\%\d:]+)*\n', r'\1,\2 --> \3,\4\n',
    #                     replacement)
    #replacement = re.sub(r'WEBVTT\n', '', replacement)
    #replacement = re.sub(r'Kind:[ \-\w]+\n', '', replacement)
    #replacement = re.sub(r'Language:[ \-\w]+\n', '', replacement)
    #replacement = re.sub(r'<c[.\w\d]*>', '', replacement)
    #replacement = re.sub(r'</c>', '', replacement)
    #replacement = re.sub(r'<\d\d:\d\d:\d\d.\d\d\d>', '', replacement)
    #replacement = re.sub(r'::[\-\w]+\([\-.\w\d]+\)[ ]*{[.,:;\(\) \-\w\d]+\n }\n', '', replacement)
    #replacement = re.sub(r'Style:\n##\n', '', replacement)

I was able to download the subtitles in "ttml" format and "smi" format, and I was able to download the subtitles in "webvtt" format too when I replaced "vtt" with "webvtt" in `utils.py` and `hulu_subs_dl.py`.

**Comment by Xonshiz** [comment]
Closing this, as same as #29 . Discussions will follow there.
