### ISSUE TITLE
Windows 10: Error when attempting to download subs in the vtt format.

### ISSUE THREAD

**Issue by clayton-grey** [Xonshiz/Hulu-Subs-Downloader#29]
OS: Windows 10
Version: EXE

When attempting to save vtt files, I received the following error:

```
Downloading Subtitle For The Great North - S1E1 [en Sub].vtt
Couldn't find vtt in Hulu
```

The error repeated for each episode, finishing with registering an error log. Using the following URL:

`https://www.hulu.com/series/great-north-374cdbc2-3b08-4b81-a68f-a45a70665849`

**Comment by Xonshiz** [comment]
Attaching #28  here for further discussion.

**Comment by Xonshiz** [comment]
I created a temp account but since I'm not in USA, it's not letting me make payments. I'll need to put this one on hold until I get an account to debug this issue.

**Comment by Xonshiz** [comment]
Should be fixed with the latest commit.
