### ISSUE TITLE
Season and episode number added to the movie subtitle

### ISSUE THREAD

**Issue by ghost** [Xonshiz/Hulu-Subs-Downloader#31]
When I try to download a movie subtitle the number of the season and episode added to the name of the subtitle file and a season folder created like.

C:\Hulusubs_dl\Terminator - Dark Fate\01\Terminator - Dark Fate - S01E01 [en Sub].srt

https://www.hulu.com/movie/terminator-dark-fate-3be9a47d-4a50-447a-980a-e5cae615f522

my operating system is Windows 10, and I'm using a Windows EXE Binary.

> C:\Hulusubs_dl>Hulusubs_dl.exe -v
***Starting the script in Verbose Mode***
Enter Hulu URL : https://www.hulu.com/movie/terminator-dark-fate-3be9a47d-4a50-447a-980a-e5cae615f522
Reading Configuration File.
Downloading Subtitle For Terminator - Dark Fate - S01E01 [en Sub].srt
> C:\Hulusubs_dl>

Hulusubs_dl_Error_Log

[Hulusubs_dl_Error_Log.zip](https://github.com/Xonshiz/Hulusubs_dl/files/6604572/Hulusubs_dl_Error_Log.zip)

**Comment by ghost** [comment]
@Xonshiz I'm really sorry, just one thing still needed to be done, If the file is a subtitle for a movie the season folder should not be created, for the movie It should be

`                        path_created = path_util.create_paths(
                            download_location + os.sep + series_name)`

It should be

C:\Hulusubs_dl\Terminator - Dark Fate\Terminator - Dark Fate [English Sub].srt

And sorry for forgetting to open a new issue before, sometimes I forgot posting in GitHub is different than posting in a forum, and really thank you for your hard work in this script.

**Comment by Xonshiz** [comment]
Ah crap, I should've seen this scenario. Thanks for pointing this out. I'll fix it later tonight.

Re-opening this bug.

**Comment by Xonshiz** [comment]
Checked in a fix for this, should fix in the latest binary.
