### ISSUE TITLE
Renaming Issue

### ISSUE THREAD

**Issue by starbez** [Xonshiz/Hulu-Subs-Downloader#32]
Season 02 has Dub which has cc that I want to download but can't because when I paste the link it download cc but since it also has Subtitled version and replaces with eng sub. is there a way where the filename could be change for Dub and Sub?
https://www.hulu.com/series/the-irregular-at-magic-high-school-80e76834-7c30-45fe-bcaa-1f4ace6a99da

**Comment by Essam3111** [comment]
Adding the name of the episode to the subtitle file could help in preventing the CC files from being overwritten by the subtitles, this could be done by replacing in `hulu.py` 

                    video_metadata = dict(list(video_metadata)[0])
                    series_name = utils.get_clean_path_name(video_metadata.get('series_name', video_metadata.get("name", "No Name Found")))
                    is_movie = True if video_metadata.get('_type', None) == "movie" else False
                    season_number = video_metadata.get('season', "01")
                    episode_number = video_metadata.get('number', "01")
                    file_name = '{0} - S{1}E{2} [{3} Sub].{4}'.format(series_name, season_number, episode_number, utils.get_language_name(language), extension)

with

                    video_metadata = dict(list(video_metadata)[0])
                    series_name = utils.get_clean_path_name(video_metadata.get('series_name', video_metadata.get("name", "No Name Found")))
                    episode_name = utils.get_clean_path_name(video_metadata.get('episode_name', video_metadata.get("name", "No Name Found")))
                    is_movie = True if video_metadata.get('_type', None) == "movie" else False
                    season_number = video_metadata.get('season', "01")
                    episode_number = video_metadata.get('number', "01")
                    file_name = '{0} - S{1}E{2} - {3} - [{4} Sub].{5}'.format(series_name, season_number, episode_number, episode_name, utils.get_language_name(language), extension)

and the name of the subtitle file will be

The Irregular at Magic High School - S2E1 - (Dub) Visitor Arc I - [English Sub].srt

and

The Irregular at Magic High School - S2E1 - (Sub) Visitor Arc I - [English Sub].srt

Or might be done by adding CC to the name of the file if the language of the "audio_tracks" in the playlist is the same as the language of subtitle, something like

The Irregular at Magic High School - S2E1 [English Sub].CC.srt

`"audio_tracks":[{"language":"en","role":"primary","codecs_string":"mp4a.40.5","channels":2}]`

**Comment by Xonshiz** [comment]
Adding the full episode name isn't a good idea because of many reasons, 2 of which I could say right off the top of my head.
1.) There's a max character limit on naming a file and is different on all OS.
2.) Doesn't look neat.

With that being said, I'll see what I can do about this DUB and SUB naming of the files. Let's see if I can get some time on this weekend to look into this.

**Comment by Tridagger** [comment]
> Adding the full episode name isn't a good idea because of many reasons, 2 of which I could say right off the top of my head.
> 1.) There's a max character limit on naming a file and is different on all OS.
> 2.) Doesn't look neat.
> 
> With that being said, I'll see what I can do about this DUB and SUB naming of the files. Let's see if I can get some time on this weekend to look into this.

![image](https://user-images.githubusercontent.com/9511835/121450279-03417700-c9ce-11eb-9ca8-ecd87f4ded89.png)
I want to download dub subtitles, I add these codes for filtering sub subtitles. You can set a switch.

**Comment by Xonshiz** [comment]
This is one way to, but, not trustworthy. Let's say "(Sub)" comes in some title.. might not indicate that the subtitle indeed is for a SUB/DUB episode. I can write this as a temporary workaround, but, it's a bit flimsy fix.

I don't have an account, I'll see if anyone can share one and I'll see if there's a surefire way to verify the subtitles. If I don't get any account, I'll push this as a workaround fix.

**Comment by Xonshiz** [comment]
Couldn't log into Hulu to compare the JSONs. As a workaround, this should hold for a while.
