### ISSUE TITLE
Keep Getting "Whoops! Seems like I can't connect to website. It's showing : <Response [400]>"

### ISSUE THREAD

**Issue by MapGuy11** [Xonshiz/Hulu-Subs-Downloader#33]
I am not quite sure what you need so let me know and I will promptly respond.

**Comment by Xonshiz** [comment]
Hmm, 400 means bad request. Would need to check. Could you post the full command you used?
Also, add `--verbose` to the full command and it'll generate an error log... post the contents of that file here.
Also, read the `[How to open issues](https://github.com/Xonshiz/Hulusubs_dl#opening-issues)` and add the info mentioned there.

Thanks

**Comment by MapGuy11** [comment]
1. OS (Windows)
2. OS Version (Windows 11 PRO)
3. Version (Windows EXE Binary)
4. URL (https://www.hulu.com/watch/627fb9e1-15a6-4b78-b256-bea6d524111d)
5. Whoops! Seems like I can't connect to website. It's showing : <Response [400]>
6.
[Hulusubs_dl_Error_Log.log](https://github.com/Xonshiz/Hulusubs_dl/files/7316683/Hulusubs_dl_Error_Log.log)
 
Config:

{'max_tries_for_cookie': '2', 'download_location': 'C:\\Users\\{USER}\\Documents\\{FINALFOLDER}', 'subtitle_lang': 'en;es', 'subtitle_extension': 'srt', 'proxies': ''}

**Comment by Xonshiz** [comment]
Thanks for the info man. I'll take a look as soon as I get some time.

**Comment by MapGuy11** [comment]
> Thanks for the info man. I'll take a look as soon as I get some time.

Take your time.
