### ISSUE TITLE
[ENHANCEMENT] Keep the original subtitle file

### ISSUE THREAD

**Issue by aaaxx** [Xonshiz/Hulu-Subs-Downloader#5]
It would be useful to also save the original file grabbed from Hulu, alongside the converted SRT files. They seem to use VTT at the moment, but regardless of the format now or in the future it would be best to always keep the raw file because it will contain all the original information that could be potentially lost when converting to other formats.

For example, there are some advanced positioning and formatting options in VTT that SRT doesn't support. Also, VTT is currently being specified as the web standard and is gaining ground in browsers and media players, and it seems quite possible it could become the SRT successor in the next few years.

**Comment by Xonshiz** [comment]
Currently VTT isn't supported by most (if not all) video players. That was the reason I did not keep it. Plus, Hulu doesn't really use any `advance positioning and formatting option`.

90-95% people don't even know how to get VTT working as well. So, to save everyone's time, VTT will be deprecated for the time being.

**Comment by Xonshiz** [comment]
VTT support has been added in the script.
