### ISSUE TITLE
batch wont download the season only single episodes.

### ISSUE THREAD

**Issue by DevanFischer** [Xonshiz/Hulu-Subs-Downloader#8]
i have done everything and it still will only download single episodes

**Comment by Xonshiz** [comment]
Please check the "Read Me". It clearly mentions this issue 
"Note : Hulu won't let logged out users to access the "Links" to single episodes. This caused the batch subs ripper to be shut down. This will definitely take a shit load amount of time to fix. I'll have to figure out a workaround for this."
