### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by taitaigip** [Xonshiz/Hulu-Subs-Downloader#9]
This was working yesterday, but not today :(

Perhaps Hulu changed their schema.

```$ cd ~/Desktop/Hulu-Subs-Downloader-master/
$ source ./venv/bin/activate
(venv) $ python HuluSubsDownloader.py 
Enter a URL : https://www.hulu.com/watch/444514            
Which format do you want : vtt
Traceback (most recent call last):
  File "HuluSubsDownloader.py", line 97, in <module>
    SubDownloader = HuluSubs(mainurl)
  File "HuluSubsDownloader.py", line 23, in __init__
    self.singleEpisode(self.url)
  File "HuluSubsDownloader.py", line 33, in singleEpisode
    episode_number = str(re.search('\"episodeNumber\"(.*?)\,', html_content).group(1)).replace(':','').replace('\\n','').strip()
AttributeError: 'NoneType' object has no attribute 'group'```

**Comment by Xonshiz** [comment]
Maybe they did. I'll take a look at this in a day or two.

**Comment by eyalaa** [comment]
Problem with AttributeError: 'NoneType' object has no attribute 'group'``` is persistant.
Anything new on this, or workaround?

Thanks!

**Comment by Xonshiz** [comment]
Hey. Just got time to look around and seems like Hulu now needs you to sign in and be in USA to even give out the subtitle ID. Unfortunately, I neither have the account and nor I am in USA.
Well, USA thing can be bypassed, but no credentials will pose a problem.

**Comment by Xonshiz** [comment]
Okay, my previous conclusion about "Signing In" and "USA" proxy for single episodes was wrong and I have successfully fixed the script. Get the fresh Python code and Fresh windows binary from the respective sections.
